export const ADD_TODO = 'ADD_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY_TITLE = 'EDIT_CATEGORY_TITLE';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';